name: Deploy with Terragrunt in Multiregion

on:
  push:
    branches:
      - test  # Ejecuta el workflow solo cuando se haga un push a la rama test


jobs:  
  deploy:
    runs-on: ubuntu-latest
    
    #strategy:
    #    matrix:
    #      region: ['eu-west-3a', 'eu-west-3b']  # Añade las regiones que deseas desplegar
  
    steps:
      # 1. Configurar el repositorio
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Configurar credenciales de AWS
      - name: Configure AWS credentials
        run: |
          mkdir -p ~/.aws          
          echo "[profile ${{ secrets.AWS_PROFILE }}]" > ~/.aws/config
          echo "region = eu-west-3" >> ~/.aws/config          
          echo "output = json" >> ~/.aws/config

          echo "[${{ secrets.AWS_PROFILE }}]" > ~/.aws/credentials
          echo "aws_access_key_id = ${{ secrets.AWS_ACCESS_KEY_ID }}" >> ~/.aws/credentials
          echo "aws_secret_access_key = ${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> ~/.aws/credentials          
          echo "aws_session_token = ${{ secrets.AWS_SESSION_TOKEN }}" >> ~/.aws/credentials
        

      # 3. Instalar terraform
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.10.0  # Cambia según la versión que necesites

      # 4. Instalar Terragrunt
      - name: Install Terragrunt
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip
          curl -L -o terragrunt https://github.com/gruntwork-io/terragrunt/releases/download/v0.35.16/terragrunt_linux_amd64
          chmod +x terragrunt
          sudo mv terragrunt /usr/local/bin/

      # 5. Verificar version Terraform
      - name: Verify Terraform version
        run: | 
          terraform --version

      # 6. Verificar version Terragrunt
      - name: Verify Terragrunt version
        run: | 
          terragrunt --version

      # 7. Verificar la existencia del directorio y permisos
      - name: Verify directory and permissions
        run: | 
          if [ ! -d "application_ha/dev" ]; then 
            echo "Directory application_ha/dev does not exist."
            exit 1 
          fi
          cd application_ha/dev
          if [ ! -x "$(command -v terragrunt)" ]; then
            echo "Terragrunt is not installed or not executable."
            exit 1
          fi

      # 8. Configurar la clave SSH
      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AWS_SSH_KEY }}" > ~/.ssh/my-aws-key.pem
          chmod 600 ~/.ssh/my-aws-key.pem
        
        env:
          aws_ssh_key: ${{ secrets.AWS_SSH_KEY }}

      # 11. Destruir Terragrunt
      #- name: Destroy with Terragrunt
        #run: |
          #cd application_ha/dev          
          #terragrunt init                 
          #terragrunt plan -destroy -out=tfplan  
          #terragrunt show tfplan               
          #terragrunt destroy -auto-approve || echo "Destroy step failed, continuing."
           

      # 9. Destruir recursos en region_1
      #- name: Destroy resources in region_1
        #run: |
          #cd application_ha/dev
          #TFVARS_FILE=region_1.tfvars terragrunt init
          #TFVARS_FILE=region_1.tfvars terragrunt plan -destroy -out=tfplan
          #TFVARS_FILE=region_1.tfvars terragrunt apply -auto-approve

      # 10. Destruir recursos en region_2
      #- name: Destroy resources in region_2
        #run: |
          #cd application_ha/dev
          #TFVARS_FILE=region_2.tfvars terragrunt init
          #TFVARS_FILE=region_2.tfvars terragrunt plan -destroy -out=tfplan
          #TFVARS_FILE=region_2.tfvars terragrunt apply -auto-approve


      
      # 11. Diagnóstico del estado
      #- name: Check Terraform State
        #run: |
          #cd application_ha/dev
          #terragrunt state list  

      
      # 12. Deploy recursos en region_1
      - name: Deploy resources in region_1
        run: |
          cd application_ha/dev
          terragrunt init --terragrunt-working-dir=eu-west-3a
          terragrunt apply --terragrunt-working-dir=eu-west-3a -auto-approve
        #  terragrunt init
        #  terragrunt apply -var-file=region_1.tfvars -auto-approve
        #  TFVARS_FILE=region_1.tfvars terragrunt init
        #  TFVARS_FILE=region_1.tfvars terragrunt apply -auto-approve

      # 13. Deploy recursos en region_2
      - name: Deploy resources in region_2
        run: |
          cd application_ha/dev
          erragrunt init --terragrunt-working-dir=eu-west-3b
          terragrunt apply --terragrunt-working-dir=eu-west-3b -auto-approve
        #  terragrunt init
        #  terragrunt apply -var-file=region_2.tfvars -auto-approve
        #  TFVARS_FILE=region_2.tfvars terragrunt init
        #  TFVARS_FILE=region_2.tfvars terragrunt apply -auto-approve


      # 9. Destruir recursos con Terragrunt
      #- name: Destroy with Terragrunt
        #run: |
          #cd application_ha/dev
          #terragrunt init
          #terragrunt plan -destroy -out=tfplan  
          #terragrunt show tfplan
          #terragrunt apply -var-file=region_1.tfvars -auto-approve
          #terragrunt apply -var-file=region_2.tfvars -auto-approve
          
        #  terragrunt apply -auto-approve || echo "Apply step failed, continuing."
          
        # terragrunt apply -var-file=region_1.tfvars -auto-approve
        # terragrunt apply -var-file=region_2.tfvars -auto-approve
           
          
      #   terragrunt apply -var-file=region_1.tfvars -auto-approve
      #   terragrunt apply -var-file=region_2.tfvars -auto-approve  
      #   terragrunt apply -var="region=eu-west-3a" -auto-approve
      #   terragrunt apply -var="region=eu-west-3b" -auto-approve  

      #  terragrunt destroy -auto-approve || echo "Destroy step failed, continuing."



      # 11. Deploy Terragrunt
      #- name: Deploy with Terragrunt
        #run: |
          #cd application_ha/dev          
          #terragrunt init
          #terragrunt apply -var-file=region_1.tfvars -auto-approve
          #terragrunt apply -var-file=region_2.tfvars -auto-approve 







    # TFVARS_FILE=region_2.tfvars terragrunt apply -auto-approve

      #   terragrunt apply -var="region=eu-west-3a" -auto-approve
      #   terragrunt apply -var="region=eu-west-3b" -auto-approve

     # Otra forma de implementar
      # 11. Deploy en la región eu-west-3a
      #- name: Deploy in eu-west-3a
        #run: |
          #export AWS_REGION=eu-west-3a
          #cd application_ha/dev          
          #terragrunt init
          #terragrunt apply -auto-approve

      # 12. Deploy en la región eu-west-3b
      #- name: Deploy in eu-west-3b
        #run: |
          #export AWS_REGION=eu-west-3b
          #cd application_ha/dev          
          #terragrunt init
          #terragrunt apply -auto-approve

      # 13. Otra forma de despliegue:
      #  - name: Deploy to ${matrix.region}
      #  run: |
      #    cd application_ha/${matrix.region}
      #    terragrunt init
      #    terragrunt apply -auto-approve



# -----------------------------------------------------------------------------------------------#