name: Deploy with Terragrunt

on:
  push:
    branches:
      - test  # Ejecuta el workflow solo cuando se haga un push a la rama test

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Configurar el repositorio
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Configurar credenciales de AWS
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: eu-west-3  # Cambia la región según tu configuración
          aws-profile: ${{ secrets.AWS_PROFILE }}  # Usa el perfil almacenado en los secretos

      # 3. Instalar terraform
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.10.0  # Cambia según la versión que necesites

      # 4. Instalar Terragrunt
      - name: Install Terragrunt
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip
          curl -L -o terragrunt https://github.com/gruntwork-io/terragrunt/releases/download/v0.35.16/terragrunt_linux_amd64
          chmod +x terragrunt
          sudo mv terragrunt /usr/local/bin/

      # 5. Verificar version Terraform
      - name: Verify Terraform version
        run: | 
          terraform --version

      # 6. Verificar version Terragrunt
      - name: Verify Terragrunt version
        run: | 
          terragrunt --version

      # 7. Verificar la existencia del directorio y permisos
      - name: Verify directory and permissions
        run: | 
          if [ ! -d "terragrunt_wordpress/dev" ]; then 
            echo "Directory terragrunt_wordpress/dev does not exist."
            exit 1 
          fi
          cd terragrunt_wordpress/dev
          if [ ! -x "$(command -v terragrunt)" ]; then
            echo "Terragrunt is not installed or not executable."
            exit 1
          fi

      # 7.5. Configurar la clave SSH
      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AWS_SSH_KEY }}" > ~/.ssh/my-aws-key.pem
          chmod 600 ~/.ssh/my-aws-key.pem
        ## Optional: Add AWS host to known_hosts to prevent SSH warnings
        #  ssh-keyscan -H <YOUR_AWS_IP> >> ~/.ssh/known_hosts
        env:
          aws_ssh_key: ${{ secrets.AWS_SSH_KEY }}

      # 8. Ejecutar Terragrunt
      - name: Deploy with Terragrunt
        run: |
          cd terragrunt_wordpress/dev 
          ls -la
          terragrunt init
          terragrunt apply -auto-approve
        #terragrunt init
        #terragrunt apply -auto-approve
        #export TERRAGRUNT_TFPATH=/home/runner/work/_temp/770842be-e026-4e5c-b43e-883c6f5b113d/terraform-bin
    