name: Deploy Infrastructure

on:
  push:
    branches:
      - develop

jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0  

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: eu-west-3

      - name: Deploy with Terraform
        run: |
          terraform init

      - name: Validate Terraform
        run: |
          terraform validate

      - name: Deploy resoruces
        run: |
            terraform plan -var-file="main.tfvars" -out=tfplan

      - name: Sync files to S3
        run: |
          aws s3 sync tfplan/ s3://${{ env.BUCKET_NAME }}

      # - name: Upload tfplan artifact
      #   uses: actions/upload-artifact@v3
      #   with:
      #       name: s3-tfplan
      #       path: tfplan
  apply:
    runs-on: ubuntu-latest
    needs: plan
    environment: production  # Specify the environment for approval
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.5.0
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: eu-west-3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan